# Generated by Django 5.1.6 on 2025-02-10 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_author_article_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('perex', models.TextField()),
                ('text', models.TextField()),
                ('published', models.DateTimeField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='games', to='content.author')),
                ('categories', models.ManyToManyField(related_name='games', to='content.category')),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
