# Generated by Django 5.1.4 on 2025-03-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0011_comment_ip_comment_time_comment_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='votes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='votes_sum',
            field=models.IntegerField(default=0),
        ),
    ]
